### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by lucas7788** [tomoya92/pybbs-go#14]
错误一：在mysql数据库里创建数据库名字叫pybbs-go
数据库的名字应该是pybbs_go，
错误二：
导入数据库失败
见截图
<img width="731" alt="2017-11-10 11 05 30" src="https://user-images.githubusercontent.com/13885466/32641130-45ea989e-c607-11e7-9388-18896e09a9cb.png">

错误三，bee run失败
见截图
<img width="899" alt="2017-11-10 11 06 06" src="https://user-images.githubusercontent.com/13885466/32641136-4a37fc2a-c607-11e7-97cf-819a9d879e51.png">

**Comment by tomoya92** [comment]
刚clone了代码运行了一下，没问题

mysql里是可以创建pybbs-go名字的，程序里连接数据库的url配置的也是pybbs-go这个名字，所以你把pybbs-go改成了pybbs_go，程序就起不来了

你要是想把pybbs-go改成pybbs_go，需要修改一下main.go里的这段代码
```
orm.RegisterDataBase("default", "mysql", beego.AppConfig.String("jdbc.username") + ":" + beego.AppConfig.String("jdbc.password") + "@/pybbs-go?charset=utf8&parseTime=true&charset=utf8&loc=Asia%2FShanghai", 30)
```
把里面的pybbs-go改成pybbs_go即可，启动的时候如果正常，会有创建表的sql语句打印出来
