### ISSUE TITLE
缺少相关库

### ISSUE THREAD

**Issue by 929496959** [tomoya92/pybbs-go#22]
app\nc\ArticleAdd.go:5:2: github.com/123456/c_code@v0.0.0-00010101000000-000000000000: replacement directory E:\codeing\go\c_code does not exist
app\nc\ArticleAdd.go:6:2: github.com/123456/c_code@v0.0.0-00010101000000-000000000000: replacement directory E:\codeing\go\c_code does not exist

**Comment by tomoya92** [comment]
我在开发过程中并没有看到这个库。。

**Comment by 929496959** [comment]
发错地址了
