### ISSUE TITLE
请问你是 youtube播放视频倍速自定义，可记忆 作者吗

### ISSUE THREAD

**Issue by mask520** [tomoya92/pybbs-go#23]
https://greasyfork.org/zh-CN/scripts/381176-youtube%E6%92%AD%E6%94%BE%E8%A7%86%E9%A2%91%E5%80%8D%E9%80%9F%E8%87%AA%E5%AE%9A%E4%B9%89-%E5%8F%AF%E8%AE%B0%E5%BF%86
请问你是 youtube播放视频倍速自定义，可记忆 作者吗

**Comment by atjiu** [comment]
怎么找到这来了 😂 

已经修了
