### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by mahuaibo** [tomoya92/pybbs-go#3]
如何进行打包发布呢？我用了bee pack 进行打包之后，发现不能用了！求大神帮助

**Comment by tomoya92** [comment]
我还真没试过打包, 项目用的就是beego, 打包应该也是用bee就可以打的, 你再多试试, 根据错误排查一下

**Comment by tomoya92** [comment]
@mahuaibo 我试了一下bee pack ，打包好了之后，解压出来，可以拷贝到任意地方，运行`pybbs-go`即可跑起来了

**注意，不要输入`./pybbs-go`去运行，这样是有问题的**

**Comment by mahuaibo** [comment]
@tomoya92  谢谢，我之前确实是用的 ./pybbs-go 去运行的
