### ISSUE TITLE
Use casbin as the permission backend

### ISSUE THREAD

**Issue by hsluoyz** [tomoya92/pybbs-go#4]
Hi, there is a project called [casbin](https://github.com/hsluoyz/casbin). It is an authorization library that supports models like MAC, RBAC, ABAC. Maybe it can assist your need in the perm management.

**Comment by hsluoyz** [comment]
PR is here: https://github.com/tomoya92/pybbs-go/pull/6

**Comment by hsluoyz** [comment]
Thanks for using casbin! Any related questions or issues please contact me at: https://github.com/hsluoyz/casbin

**Comment by tomoya92** [comment]
thx
