### ISSUE TITLE
数据库导入问题

### ISSUE THREAD

**Issue by lg430** [tomoya92/pybbs-go#8]
提供的sql文件并没有创建结构部分, 能重新导出一份sql吗

**Comment by tomoya92** [comment]
表是自动创建的。。。。。。。。。。。。。。。。

**Comment by lg430** [comment]
![image](https://cloud.githubusercontent.com/assets/7238625/25791430/d640b092-33f2-11e7-9dd2-9ecd1be1e413.png)

**Comment by tomoya92** [comment]
@lg430 你有好好看readme操作吗？

**Comment by lg430** [comment]
好的, 我疏忽了
